[package]
name = "foobar"
version = "0.1.0"
authors = ["Alex Kesling <alex@kesling.co>"]
edition = "2018"

[dependencies]
bytes = "0.4"
futures = "^0.1.*"
prost = "0.5"
tonic = "0.1.0-alpha.6"

[build-dependencies]
tonic-build = "0.1.0-alpha.6"
